### ISSUE TITLE
Class Names largely changed

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [filipw/Roslyn.WebApi.IssueExample#1]
CommonSyntaxNode, CodeIssue, and more
classes no longer exist

IDocument and more
interfaces no longer exist

**Comment by filipw** [comment]
this was built 3 years ago, against Roslyn preview from 3.5 years ago :)
Ever since Roslyn has changed dramatically, yes

**Comment by ImaginaryDevelopment** [comment]
Looks like
CommonSyntaxNode -> ExpressionSyntax
CodeIssue -> Diagnostic
IDocument -> Document

is what I've discovered so far.
